export interface Invoice {
  id: string;
  studentId: string;
  studentName: string;
  class: string;
  session: string;
  baseFee: number;
  discountType: string | null;
  discountValue: number;
  discountAmt: number;
  finalAmt: number;
  status: "paid" | "pending" | "overdue" | "partial" | "cancelled";
  dueDate: string;
  paidDate: string | null;
  method: string | null;
  paidAmt?: number;
}

export interface Payment {
  id: string;
  invoiceId: string;
  studentName: string;
  amount: number;
  date: string;
  method: string;
  receivedBy: string;
  note: string;
}

export interface HasanatPayout {
  id: string;
  studentId: string;
  studentName: string;
  class: string;
  pointsEarned: number;
  pointsRedeemed: number;
  rewardGiven: string | null;
  date: string | null;
  approvedBy: string | null;
}

export interface FinanceSettings {
  currency: string;
  invoicePrefix: string;
  dueDays: string;
  lateFeePercent: string;
  taxRate: string;
  paymentMethods: string[];
  autoGenerateInvoice: boolean;
  sendInvoiceEmail: boolean;
  allowPartialPayment: boolean;
  requireApproval: boolean;
  overdueReminder: boolean;
  reminderDaysBefore: string;
  feeReminders: boolean;
}

export const DEFAULT_FINANCE_SETTINGS: FinanceSettings = {
  currency: "PKR",
  invoicePrefix: "INV",
  dueDays: "30",
  lateFeePercent: "5",
  taxRate: "0",
  paymentMethods: ["cash", "bank_transfer"],
  autoGenerateInvoice: true,
  sendInvoiceEmail: true,
  allowPartialPayment: true,
  requireApproval: false,
  overdueReminder: true,
  reminderDaysBefore: "3",
  feeReminders: true
};

export const INVOICES: Invoice[] = [
  {
    "id": "inv001",
    "studentId": "st1",
    "studentName": "Abdullah Rizvi",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 350,
    "finalAmt": 3150,
    "status": "paid",
    "dueDate": "2025-06-11",
    "paidDate": "2025-06-04",
    "method": "Bank Transfer",
    "paidAmt": 3150
  },
  {
    "id": "inv002",
    "studentId": "st2",
    "studentName": "Usman Hussain",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "partial",
    "dueDate": "2025-07-20",
    "paidDate": "2025-06-30",
    "method": "Online",
    "paidAmt": 1750
  },
  {
    "id": "inv003",
    "studentId": "st4",
    "studentName": "Shakir Ghani",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-07-26",
    "paidDate": "2025-06-18",
    "method": "Bank Transfer",
    "paidAmt": 3500
  },
  {
    "id": "inv004",
    "studentId": "st5",
    "studentName": "Jabir Raza",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 875,
    "finalAmt": 2625,
    "status": "paid",
    "dueDate": "2025-08-03",
    "paidDate": "2025-07-12",
    "method": "Cash",
    "paidAmt": 2625
  },
  {
    "id": "inv005",
    "studentId": "st6",
    "studentName": "Sumayya Iqbal",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 400,
    "finalAmt": 3600,
    "status": "pending",
    "dueDate": "2025-06-14",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv006",
    "studentId": "st7",
    "studentName": "Safiyyah Nawaz",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 2500,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-06-29",
    "paidDate": "2025-06-14",
    "method": "Online",
    "paidAmt": 0
  },
  {
    "id": "inv007",
    "studentId": "st8",
    "studentName": "Samia Hashmi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "pending",
    "dueDate": "2025-07-31",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv008",
    "studentId": "st9",
    "studentName": "Zain Zaidi",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-07-17",
    "paidDate": "2025-06-24",
    "method": "Bank Transfer",
    "paidAmt": 3500
  },
  {
    "id": "inv009",
    "studentId": "st10",
    "studentName": "Hina Aslam",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-06-14",
    "paidDate": "2025-06-13",
    "method": "Bank Transfer",
    "paidAmt": 4000
  },
  {
    "id": "inv010",
    "studentId": "st11",
    "studentName": "Hassan Al-Nouri",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-06-17",
    "paidDate": "2025-06-09",
    "method": "Online",
    "paidAmt": 3500
  },
  {
    "id": "inv011",
    "studentId": "st12",
    "studentName": "Zakariya Naqvi",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-07-23",
    "paidDate": "2025-06-02",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv012",
    "studentId": "st13",
    "studentName": "Samia Karimi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 1000,
    "finalAmt": 3000,
    "status": "pending",
    "dueDate": "2025-07-17",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv013",
    "studentId": "st14",
    "studentName": "Lubna Karimi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-07-03",
    "paidDate": "2025-06-29",
    "method": "Online",
    "paidAmt": 4000
  },
  {
    "id": "inv014",
    "studentId": "st15",
    "studentName": "Aaliyah Ghani",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2500,
    "status": "paid",
    "dueDate": "2025-06-13",
    "paidDate": "2025-06-03",
    "method": "Bank Transfer",
    "paidAmt": 2500
  },
  {
    "id": "inv015",
    "studentId": "st16",
    "studentName": "Harun Khalid",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-06-20",
    "paidDate": "2025-06-13",
    "method": "Bank Transfer",
    "paidAmt": 3500
  },
  {
    "id": "inv016",
    "studentId": "st17",
    "studentName": "Bushra Bukhari",
    "class": "Islamic Studies Yr 1",
    "session": "Islamic Studies Program",
    "baseFee": 2000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2000,
    "status": "paid",
    "dueDate": "2025-06-10",
    "paidDate": "2025-06-03",
    "method": "Cash",
    "paidAmt": 2000
  },
  {
    "id": "inv017",
    "studentId": "st19",
    "studentName": "Lubna Shafique",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 2500,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-06-09",
    "paidDate": "2025-06-08",
    "method": "Cash",
    "paidAmt": 0
  },
  {
    "id": "inv018",
    "studentId": "st20",
    "studentName": "Safiyyah Tariq",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 625,
    "finalAmt": 1875,
    "status": "paid",
    "dueDate": "2025-08-07",
    "paidDate": "2025-06-15",
    "method": "Cash",
    "paidAmt": 1875
  },
  {
    "id": "inv019",
    "studentId": "st21",
    "studentName": "Zara Khalid",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2500,
    "status": "paid",
    "dueDate": "2025-08-05",
    "paidDate": "2025-06-20",
    "method": "Bank Transfer",
    "paidAmt": 2500
  },
  {
    "id": "inv020",
    "studentId": "st22",
    "studentName": "Noman Aslam",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-07-22",
    "paidDate": "2025-06-24",
    "method": "Online",
    "paidAmt": 3500
  },
  {
    "id": "inv021",
    "studentId": "st23",
    "studentName": "Sidra Al-Rashid",
    "class": "Islamic Studies Yr 1",
    "session": "Islamic Studies Program",
    "baseFee": 2000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2000,
    "status": "paid",
    "dueDate": "2025-06-30",
    "paidDate": "2025-06-18",
    "method": "Bank Transfer",
    "paidAmt": 2000
  },
  {
    "id": "inv022",
    "studentId": "st24",
    "studentName": "Jamil Kazmi",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 3500,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-07-01",
    "paidDate": "2025-06-03",
    "method": "Online",
    "paidAmt": 0
  },
  {
    "id": "inv023",
    "studentId": "st25",
    "studentName": "Bashir Al-Nouri",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-06-10",
    "paidDate": "2025-06-03",
    "method": "Online",
    "paidAmt": 3500
  },
  {
    "id": "inv024",
    "studentId": "st26",
    "studentName": "Kashif Shah",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-07-11",
    "paidDate": "2025-06-23",
    "method": "Bank Transfer",
    "paidAmt": 3500
  },
  {
    "id": "inv025",
    "studentId": "st27",
    "studentName": "Maryam Hashmi",
    "class": "Islamic Studies Yr 1",
    "session": "Islamic Studies Program",
    "baseFee": 2000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2000,
    "status": "paid",
    "dueDate": "2025-07-15",
    "paidDate": "2025-06-17",
    "method": "Online",
    "paidAmt": 2000
  },
  {
    "id": "inv026",
    "studentId": "st28",
    "studentName": "Ayla Bukhari",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 1000,
    "finalAmt": 3000,
    "status": "overdue",
    "dueDate": "2025-07-30",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv027",
    "studentId": "st29",
    "studentName": "Luqman Rehman",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 875,
    "finalAmt": 2625,
    "status": "paid",
    "dueDate": "2025-08-06",
    "paidDate": "2025-06-21",
    "method": "Online",
    "paidAmt": 2625
  },
  {
    "id": "inv028",
    "studentId": "st30",
    "studentName": "Sufyan Imran",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 350,
    "finalAmt": 3150,
    "status": "overdue",
    "dueDate": "2025-08-08",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv029",
    "studentId": "st31",
    "studentName": "Yahya Aslam",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-06-20",
    "paidDate": "2025-06-09",
    "method": "Online",
    "paidAmt": 3500
  },
  {
    "id": "inv030",
    "studentId": "st33",
    "studentName": "Lubna Dar",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 1000,
    "finalAmt": 3000,
    "status": "paid",
    "dueDate": "2025-07-15",
    "paidDate": "2025-06-23",
    "method": "Cash",
    "paidAmt": 3000
  },
  {
    "id": "inv031",
    "studentId": "st34",
    "studentName": "Nadia Bhatti",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-08-06",
    "paidDate": "2025-06-20",
    "method": "Bank Transfer",
    "paidAmt": 4000
  },
  {
    "id": "inv032",
    "studentId": "st35",
    "studentName": "Hamza Akhtar",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-06-22",
    "paidDate": "2025-06-16",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv033",
    "studentId": "st37",
    "studentName": "Shakir Bukhari",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-08-04",
    "paidDate": "2025-06-17",
    "method": "Bank Transfer",
    "paidAmt": 3500
  },
  {
    "id": "inv034",
    "studentId": "st39",
    "studentName": "Ruqayyah Lodhi",
    "class": "Islamic Studies Yr 1",
    "session": "Islamic Studies Program",
    "baseFee": 2000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2000,
    "status": "paid",
    "dueDate": "2025-06-20",
    "paidDate": "2025-06-16",
    "method": "Bank Transfer",
    "paidAmt": 2000
  },
  {
    "id": "inv035",
    "studentId": "st40",
    "studentName": "Mustafa Pirzada",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 3500,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-06-17",
    "paidDate": "2025-06-04",
    "method": "Cash",
    "paidAmt": 0
  },
  {
    "id": "inv036",
    "studentId": "st41",
    "studentName": "Layla Aziz",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2500,
    "status": "paid",
    "dueDate": "2025-07-31",
    "paidDate": "2025-06-19",
    "method": "Bank Transfer",
    "paidAmt": 2500
  },
  {
    "id": "inv037",
    "studentId": "st44",
    "studentName": "Ali Nawaz",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-06-17",
    "paidDate": "2025-06-13",
    "method": "Bank Transfer",
    "paidAmt": 3500
  },
  {
    "id": "inv038",
    "studentId": "st45",
    "studentName": "Farida Qazi",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2500,
    "status": "paid",
    "dueDate": "2025-08-07",
    "paidDate": "2025-08-06",
    "method": "Cash",
    "paidAmt": 2500
  },
  {
    "id": "inv039",
    "studentId": "st46",
    "studentName": "Sidra Khan",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 400,
    "finalAmt": 3600,
    "status": "paid",
    "dueDate": "2025-06-11",
    "paidDate": "2025-06-03",
    "method": "Online",
    "paidAmt": 3600
  },
  {
    "id": "inv040",
    "studentId": "st47",
    "studentName": "Noman Kazmi",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 3500,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-07-09",
    "paidDate": "2025-06-22",
    "method": "Online",
    "paidAmt": 0
  },
  {
    "id": "inv041",
    "studentId": "st48",
    "studentName": "Uzma Imran",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2500,
    "status": "paid",
    "dueDate": "2025-07-09",
    "paidDate": "2025-06-20",
    "method": "Cash",
    "paidAmt": 2500
  },
  {
    "id": "inv042",
    "studentId": "st49",
    "studentName": "Ibrahim Imran",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 875,
    "finalAmt": 2625,
    "status": "paid",
    "dueDate": "2025-07-30",
    "paidDate": "2025-06-03",
    "method": "Cash",
    "paidAmt": 2625
  },
  {
    "id": "inv043",
    "studentId": "st50",
    "studentName": "Ruqayyah Shah",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 250,
    "finalAmt": 2250,
    "status": "paid",
    "dueDate": "2025-07-14",
    "paidDate": "2025-06-22",
    "method": "Online",
    "paidAmt": 2250
  },
  {
    "id": "inv044",
    "studentId": "st51",
    "studentName": "Imran Qadri",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 350,
    "finalAmt": 3150,
    "status": "paid",
    "dueDate": "2025-07-28",
    "paidDate": "2025-06-03",
    "method": "Online",
    "paidAmt": 3150
  },
  {
    "id": "inv045",
    "studentId": "st52",
    "studentName": "Zoya Pirzada",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 400,
    "finalAmt": 3600,
    "status": "pending",
    "dueDate": "2025-07-26",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv046",
    "studentId": "st53",
    "studentName": "Hassan Khalid",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 350,
    "finalAmt": 3150,
    "status": "paid",
    "dueDate": "2025-08-09",
    "paidDate": "2025-06-16",
    "method": "Online",
    "paidAmt": 3150
  },
  {
    "id": "inv047",
    "studentId": "st55",
    "studentName": "Noman Tariq",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 875,
    "finalAmt": 2625,
    "status": "paid",
    "dueDate": "2025-08-08",
    "paidDate": "2025-07-23",
    "method": "Cash",
    "paidAmt": 2625
  },
  {
    "id": "inv048",
    "studentId": "st56",
    "studentName": "Hina Anwar",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2500,
    "status": "paid",
    "dueDate": "2025-07-30",
    "paidDate": "2025-07-10",
    "method": "Online",
    "paidAmt": 2500
  },
  {
    "id": "inv049",
    "studentId": "st57",
    "studentName": "Aaliyah Qureshi",
    "class": "Islamic Studies Yr 1",
    "session": "Islamic Studies Program",
    "baseFee": 2000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2000,
    "status": "pending",
    "dueDate": "2025-06-20",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv050",
    "studentId": "st58",
    "studentName": "Hina Zahid",
    "class": "Islamic Studies Yr 1",
    "session": "Islamic Studies Program",
    "baseFee": 2000,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 2000,
    "finalAmt": 0,
    "status": "pending",
    "dueDate": "2025-07-24",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv051",
    "studentId": "st60",
    "studentName": "Zainab Siddiqui",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-06-20",
    "paidDate": "2025-06-10",
    "method": "Online",
    "paidAmt": 4000
  },
  {
    "id": "inv052",
    "studentId": "st61",
    "studentName": "Jabir Raza",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-08-01",
    "paidDate": "2025-06-04",
    "method": "Bank Transfer",
    "paidAmt": 3500
  },
  {
    "id": "inv053",
    "studentId": "st62",
    "studentName": "Maryam Malik",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 1000,
    "finalAmt": 3000,
    "status": "paid",
    "dueDate": "2025-06-22",
    "paidDate": "2025-06-04",
    "method": "Bank Transfer",
    "paidAmt": 3000
  },
  {
    "id": "inv054",
    "studentId": "st63",
    "studentName": "Sana Baig",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 250,
    "finalAmt": 2250,
    "status": "overdue",
    "dueDate": "2025-06-24",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv055",
    "studentId": "st64",
    "studentName": "Habib Ghani",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-06-13",
    "paidDate": "2025-06-08",
    "method": "Bank Transfer",
    "paidAmt": 3500
  },
  {
    "id": "inv056",
    "studentId": "st65",
    "studentName": "Jabir Sheikh",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-07-27",
    "paidDate": "2025-06-04",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv057",
    "studentId": "st66",
    "studentName": "Sumayya Nawaz",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 4000,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-06-18",
    "paidDate": "2025-06-13",
    "method": "Online",
    "paidAmt": 0
  },
  {
    "id": "inv058",
    "studentId": "st67",
    "studentName": "Ali Farooq",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "overdue",
    "dueDate": "2025-07-18",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv059",
    "studentId": "st68",
    "studentName": "Rida Al-Nouri",
    "class": "Islamic Studies Yr 1",
    "session": "Islamic Studies Program",
    "baseFee": 2000,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 500,
    "finalAmt": 1500,
    "status": "paid",
    "dueDate": "2025-06-21",
    "paidDate": "2025-06-04",
    "method": "Online",
    "paidAmt": 1500
  },
  {
    "id": "inv060",
    "studentId": "st69",
    "studentName": "Sidra Tariq",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "pending",
    "dueDate": "2025-06-23",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv061",
    "studentId": "st70",
    "studentName": "Sawdah Abbasi",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2500,
    "status": "partial",
    "dueDate": "2025-07-22",
    "paidDate": "2025-07-11",
    "method": "Online",
    "paidAmt": 1250
  },
  {
    "id": "inv062",
    "studentId": "st73",
    "studentName": "Asiya Latif",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 1000,
    "finalAmt": 3000,
    "status": "overdue",
    "dueDate": "2025-06-26",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv063",
    "studentId": "st74",
    "studentName": "Asiya Iqbal",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-07-27",
    "paidDate": "2025-07-22",
    "method": "Online",
    "paidAmt": 4000
  },
  {
    "id": "inv064",
    "studentId": "st75",
    "studentName": "Sara Yousaf",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "pending",
    "dueDate": "2025-06-25",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv065",
    "studentId": "st76",
    "studentName": "Sajid Kazmi",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-06-18",
    "paidDate": "2025-06-05",
    "method": "Online",
    "paidAmt": 3500
  },
  {
    "id": "inv066",
    "studentId": "st77",
    "studentName": "Qadir Imran",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 875,
    "finalAmt": 2625,
    "status": "paid",
    "dueDate": "2025-06-25",
    "paidDate": "2025-06-16",
    "method": "Cash",
    "paidAmt": 2625
  },
  {
    "id": "inv067",
    "studentId": "st78",
    "studentName": "Ruqayyah Karimi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 400,
    "finalAmt": 3600,
    "status": "paid",
    "dueDate": "2025-08-07",
    "paidDate": "2025-06-09",
    "method": "Online",
    "paidAmt": 3600
  },
  {
    "id": "inv068",
    "studentId": "st79",
    "studentName": "Hussein Ghani",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 875,
    "finalAmt": 2625,
    "status": "paid",
    "dueDate": "2025-06-30",
    "paidDate": "2025-06-20",
    "method": "Bank Transfer",
    "paidAmt": 2625
  },
  {
    "id": "inv069",
    "studentId": "st80",
    "studentName": "Fariha Qureshi",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 2500,
    "finalAmt": 0,
    "status": "partial",
    "dueDate": "2025-07-23",
    "paidDate": "2025-06-26",
    "method": "Cash",
    "paidAmt": 0
  },
  {
    "id": "inv070",
    "studentId": "st82",
    "studentName": "Faisal Al-Farsi",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 3500,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-08-06",
    "paidDate": "2025-08-01",
    "method": "Online",
    "paidAmt": 0
  },
  {
    "id": "inv071",
    "studentId": "st84",
    "studentName": "Muhammad Karimi",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 3500,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-07-14",
    "paidDate": "2025-06-05",
    "method": "Online",
    "paidAmt": 0
  },
  {
    "id": "inv072",
    "studentId": "st85",
    "studentName": "Yahya Farooq",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 3500,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-06-12",
    "paidDate": "2025-06-10",
    "method": "Online",
    "paidAmt": 0
  },
  {
    "id": "inv073",
    "studentId": "st86",
    "studentName": "Rayhana Ghazi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-07-20",
    "paidDate": "2025-06-26",
    "method": "Bank Transfer",
    "paidAmt": 4000
  },
  {
    "id": "inv074",
    "studentId": "st87",
    "studentName": "Sana Al-Farsi",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2500,
    "status": "paid",
    "dueDate": "2025-08-02",
    "paidDate": "2025-06-29",
    "method": "Online",
    "paidAmt": 2500
  },
  {
    "id": "inv075",
    "studentId": "st90",
    "studentName": "Zoya Rizvi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-07-03",
    "paidDate": "2025-06-09",
    "method": "Bank Transfer",
    "paidAmt": 4000
  },
  {
    "id": "inv076",
    "studentId": "st91",
    "studentName": "Aisha Rahman",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-07-12",
    "paidDate": "2025-07-09",
    "method": "Cash",
    "paidAmt": 4000
  },
  {
    "id": "inv077",
    "studentId": "st92",
    "studentName": "Bashir Malik",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-07-26",
    "paidDate": "2025-07-01",
    "method": "Online",
    "paidAmt": 3500
  },
  {
    "id": "inv078",
    "studentId": "st93",
    "studentName": "Bushra Qadri",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-06-19",
    "paidDate": "2025-06-12",
    "method": "Bank Transfer",
    "paidAmt": 4000
  },
  {
    "id": "inv079",
    "studentId": "st94",
    "studentName": "Fatima Zaidi",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 2500,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-06-11",
    "paidDate": "2025-06-06",
    "method": "Online",
    "paidAmt": 0
  },
  {
    "id": "inv080",
    "studentId": "st96",
    "studentName": "Asma Al-Rashid",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": "SCHOLARSHIP Discount",
    "discountValue": 100,
    "discountAmt": 2500,
    "finalAmt": 0,
    "status": "paid",
    "dueDate": "2025-08-01",
    "paidDate": "2025-07-08",
    "method": "Online",
    "paidAmt": 0
  },
  {
    "id": "inv081",
    "studentId": "st97",
    "studentName": "Hania Al-Nouri",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 625,
    "finalAmt": 1875,
    "status": "paid",
    "dueDate": "2025-08-03",
    "paidDate": "2025-07-02",
    "method": "Cash",
    "paidAmt": 1875
  },
  {
    "id": "inv082",
    "studentId": "st98",
    "studentName": "Yasmin Lodhi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 1000,
    "finalAmt": 3000,
    "status": "overdue",
    "dueDate": "2025-08-09",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv083",
    "studentId": "st100",
    "studentName": "Hafsa Khan",
    "class": "Islamic Studies Yr 1",
    "session": "Islamic Studies Program",
    "baseFee": 2000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2000,
    "status": "overdue",
    "dueDate": "2025-06-29",
    "paidDate": null,
    "method": null,
    "paidAmt": 0
  },
  {
    "id": "inv084",
    "studentId": "st101",
    "studentName": "Noura Hussain",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-07-11",
    "paidDate": "2025-06-28",
    "method": "Bank Transfer",
    "paidAmt": 4000
  },
  {
    "id": "inv085",
    "studentId": "st102",
    "studentName": "Sajid Sajid",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-07-26",
    "paidDate": "2025-07-06",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv086",
    "studentId": "st103",
    "studentName": "Salman Akhtar",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-07-05",
    "paidDate": "2025-06-10",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv087",
    "studentId": "st104",
    "studentName": "Salma Ghani",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-06-30",
    "paidDate": "2025-06-20",
    "method": "Bank Transfer",
    "paidAmt": 4000
  },
  {
    "id": "inv088",
    "studentId": "st105",
    "studentName": "Fatima Al-Nouri",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-07-24",
    "paidDate": "2025-06-28",
    "method": "Online",
    "paidAmt": 4000
  },
  {
    "id": "inv089",
    "studentId": "st106",
    "studentName": "Sawdah Latif",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "FINANCIAL_AID Discount",
    "discountValue": 25,
    "discountAmt": 1000,
    "finalAmt": 3000,
    "status": "paid",
    "dueDate": "2025-06-10",
    "paidDate": "2025-06-01",
    "method": "Online",
    "paidAmt": 3000
  },
  {
    "id": "inv090",
    "studentId": "st107",
    "studentName": "Bushra Yousaf",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-07-02",
    "paidDate": "2025-06-27",
    "method": "Online",
    "paidAmt": 4000
  },
  {
    "id": "inv091",
    "studentId": "st108",
    "studentName": "Ali Rahman",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-07-24",
    "paidDate": "2025-07-17",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv092",
    "studentId": "st110",
    "studentName": "Uzma Al-Farsi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": "SIBLING Discount",
    "discountValue": 10,
    "discountAmt": 400,
    "finalAmt": 3600,
    "status": "paid",
    "dueDate": "2025-08-02",
    "paidDate": "2025-06-19",
    "method": "Bank Transfer",
    "paidAmt": 3600
  },
  {
    "id": "inv501",
    "studentId": "st29",
    "studentName": "Luqman Rehman",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv502",
    "studentId": "st44",
    "studentName": "Ali Nawaz",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv503",
    "studentId": "st30",
    "studentName": "Sufyan Imran",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv504",
    "studentId": "st107",
    "studentName": "Bushra Yousaf",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 4000
  },
  {
    "id": "inv505",
    "studentId": "st107",
    "studentName": "Bushra Yousaf",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 4000
  },
  {
    "id": "inv506",
    "studentId": "st53",
    "studentName": "Hassan Khalid",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv507",
    "studentId": "st55",
    "studentName": "Noman Tariq",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv508",
    "studentId": "st102",
    "studentName": "Sajid Sajid",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv509",
    "studentId": "st15",
    "studentName": "Aaliyah Ghani",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 2500
  },
  {
    "id": "inv510",
    "studentId": "st39",
    "studentName": "Ruqayyah Lodhi",
    "class": "Islamic Studies Yr 1",
    "session": "Islamic Studies Program",
    "baseFee": 2000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2000,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 2000
  },
  {
    "id": "inv511",
    "studentId": "st106",
    "studentName": "Sawdah Latif",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 4000
  },
  {
    "id": "inv512",
    "studentId": "st55",
    "studentName": "Noman Tariq",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv513",
    "studentId": "st14",
    "studentName": "Lubna Karimi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 4000
  },
  {
    "id": "inv514",
    "studentId": "st78",
    "studentName": "Ruqayyah Karimi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 4000
  },
  {
    "id": "inv515",
    "studentId": "st22",
    "studentName": "Noman Aslam",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv516",
    "studentId": "st64",
    "studentName": "Habib Ghani",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv517",
    "studentId": "st87",
    "studentName": "Sana Al-Farsi",
    "class": "Qaidah Girls A",
    "session": "Qaidah Beginners Batch",
    "baseFee": 2500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 2500
  },
  {
    "id": "inv518",
    "studentId": "st12",
    "studentName": "Zakariya Naqvi",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv519",
    "studentId": "st76",
    "studentName": "Sajid Kazmi",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv520",
    "studentId": "st23",
    "studentName": "Sidra Al-Rashid",
    "class": "Islamic Studies Yr 1",
    "session": "Islamic Studies Program",
    "baseFee": 2000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 2000,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 2000
  },
  {
    "id": "inv521",
    "studentId": "st26",
    "studentName": "Kashif Shah",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv522",
    "studentId": "st4",
    "studentName": "Shakir Ghani",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv523",
    "studentId": "st79",
    "studentName": "Hussein Ghani",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv524",
    "studentId": "st35",
    "studentName": "Hamza Akhtar",
    "class": "Hifz A",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  },
  {
    "id": "inv525",
    "studentId": "st34",
    "studentName": "Nadia Bhatti",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 4000
  },
  {
    "id": "inv526",
    "studentId": "st110",
    "studentName": "Uzma Al-Farsi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 4000
  },
  {
    "id": "inv527",
    "studentId": "st78",
    "studentName": "Ruqayyah Karimi",
    "class": "Tajweed Adv",
    "session": "Tajweed Advanced Course",
    "baseFee": 4000,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 4000,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 4000
  },
  {
    "id": "inv528",
    "studentId": "st29",
    "studentName": "Luqman Rehman",
    "class": "Hifz B",
    "session": "Summer Hifz Programme 2025",
    "baseFee": 3500,
    "discountType": null,
    "discountValue": 0,
    "discountAmt": 0,
    "finalAmt": 3500,
    "status": "paid",
    "dueDate": "2025-09-10",
    "paidDate": "2025-09-08",
    "method": "Cash",
    "paidAmt": 3500
  }
];
export const PAYMENTS: Payment[] = [
  {
    "id": "pay001",
    "invoiceId": "inv001",
    "studentName": "Abdullah Rizvi",
    "amount": 3150,
    "date": "2025-06-04",
    "method": "Bank Transfer",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay002",
    "invoiceId": "inv002",
    "studentName": "Usman Hussain",
    "amount": 1750,
    "date": "2025-06-30",
    "method": "Online",
    "receivedBy": "Accountant",
    "note": "Partial payment, balance due"
  },
  {
    "id": "pay003",
    "invoiceId": "inv003",
    "studentName": "Shakir Ghani",
    "amount": 3500,
    "date": "2025-06-18",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay004",
    "invoiceId": "inv004",
    "studentName": "Jabir Raza",
    "amount": 2625,
    "date": "2025-07-12",
    "method": "Cash",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay005",
    "invoiceId": "inv008",
    "studentName": "Zain Zaidi",
    "amount": 3500,
    "date": "2025-06-24",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay006",
    "invoiceId": "inv009",
    "studentName": "Hina Aslam",
    "amount": 4000,
    "date": "2025-06-13",
    "method": "Bank Transfer",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay007",
    "invoiceId": "inv010",
    "studentName": "Hassan Al-Nouri",
    "amount": 3500,
    "date": "2025-06-09",
    "method": "Online",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay008",
    "invoiceId": "inv011",
    "studentName": "Zakariya Naqvi",
    "amount": 3500,
    "date": "2025-06-02",
    "method": "Cash",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay009",
    "invoiceId": "inv013",
    "studentName": "Lubna Karimi",
    "amount": 4000,
    "date": "2025-06-29",
    "method": "Online",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay010",
    "invoiceId": "inv014",
    "studentName": "Aaliyah Ghani",
    "amount": 2500,
    "date": "2025-06-03",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay011",
    "invoiceId": "inv015",
    "studentName": "Harun Khalid",
    "amount": 3500,
    "date": "2025-06-13",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay012",
    "invoiceId": "inv016",
    "studentName": "Bushra Bukhari",
    "amount": 2000,
    "date": "2025-06-03",
    "method": "Cash",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay013",
    "invoiceId": "inv018",
    "studentName": "Safiyyah Tariq",
    "amount": 1875,
    "date": "2025-06-15",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay014",
    "invoiceId": "inv019",
    "studentName": "Zara Khalid",
    "amount": 2500,
    "date": "2025-06-20",
    "method": "Bank Transfer",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay015",
    "invoiceId": "inv020",
    "studentName": "Noman Aslam",
    "amount": 3500,
    "date": "2025-06-24",
    "method": "Online",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay016",
    "invoiceId": "inv021",
    "studentName": "Sidra Al-Rashid",
    "amount": 2000,
    "date": "2025-06-18",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay017",
    "invoiceId": "inv023",
    "studentName": "Bashir Al-Nouri",
    "amount": 3500,
    "date": "2025-06-03",
    "method": "Online",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay018",
    "invoiceId": "inv024",
    "studentName": "Kashif Shah",
    "amount": 3500,
    "date": "2025-06-23",
    "method": "Bank Transfer",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay019",
    "invoiceId": "inv025",
    "studentName": "Maryam Hashmi",
    "amount": 2000,
    "date": "2025-06-17",
    "method": "Online",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay020",
    "invoiceId": "inv027",
    "studentName": "Luqman Rehman",
    "amount": 2625,
    "date": "2025-06-21",
    "method": "Online",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay021",
    "invoiceId": "inv029",
    "studentName": "Yahya Aslam",
    "amount": 3500,
    "date": "2025-06-09",
    "method": "Online",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay022",
    "invoiceId": "inv030",
    "studentName": "Lubna Dar",
    "amount": 3000,
    "date": "2025-06-23",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay023",
    "invoiceId": "inv031",
    "studentName": "Nadia Bhatti",
    "amount": 4000,
    "date": "2025-06-20",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay024",
    "invoiceId": "inv032",
    "studentName": "Hamza Akhtar",
    "amount": 3500,
    "date": "2025-06-16",
    "method": "Cash",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay025",
    "invoiceId": "inv033",
    "studentName": "Shakir Bukhari",
    "amount": 3500,
    "date": "2025-06-17",
    "method": "Bank Transfer",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay026",
    "invoiceId": "inv034",
    "studentName": "Ruqayyah Lodhi",
    "amount": 2000,
    "date": "2025-06-16",
    "method": "Bank Transfer",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay027",
    "invoiceId": "inv036",
    "studentName": "Layla Aziz",
    "amount": 2500,
    "date": "2025-06-19",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay028",
    "invoiceId": "inv037",
    "studentName": "Ali Nawaz",
    "amount": 3500,
    "date": "2025-06-13",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay029",
    "invoiceId": "inv038",
    "studentName": "Farida Qazi",
    "amount": 2500,
    "date": "2025-08-06",
    "method": "Cash",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay030",
    "invoiceId": "inv039",
    "studentName": "Sidra Khan",
    "amount": 3600,
    "date": "2025-06-03",
    "method": "Online",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay031",
    "invoiceId": "inv041",
    "studentName": "Uzma Imran",
    "amount": 2500,
    "date": "2025-06-20",
    "method": "Cash",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay032",
    "invoiceId": "inv042",
    "studentName": "Ibrahim Imran",
    "amount": 2625,
    "date": "2025-06-03",
    "method": "Cash",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay033",
    "invoiceId": "inv043",
    "studentName": "Ruqayyah Shah",
    "amount": 2250,
    "date": "2025-06-22",
    "method": "Online",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay034",
    "invoiceId": "inv044",
    "studentName": "Imran Qadri",
    "amount": 3150,
    "date": "2025-06-03",
    "method": "Online",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay035",
    "invoiceId": "inv046",
    "studentName": "Hassan Khalid",
    "amount": 3150,
    "date": "2025-06-16",
    "method": "Online",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay036",
    "invoiceId": "inv047",
    "studentName": "Noman Tariq",
    "amount": 2625,
    "date": "2025-07-23",
    "method": "Cash",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay037",
    "invoiceId": "inv048",
    "studentName": "Hina Anwar",
    "amount": 2500,
    "date": "2025-07-10",
    "method": "Online",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay038",
    "invoiceId": "inv051",
    "studentName": "Zainab Siddiqui",
    "amount": 4000,
    "date": "2025-06-10",
    "method": "Online",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay039",
    "invoiceId": "inv052",
    "studentName": "Jabir Raza",
    "amount": 3500,
    "date": "2025-06-04",
    "method": "Bank Transfer",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay040",
    "invoiceId": "inv053",
    "studentName": "Maryam Malik",
    "amount": 3000,
    "date": "2025-06-04",
    "method": "Bank Transfer",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay041",
    "invoiceId": "inv055",
    "studentName": "Habib Ghani",
    "amount": 3500,
    "date": "2025-06-08",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay042",
    "invoiceId": "inv056",
    "studentName": "Jabir Sheikh",
    "amount": 3500,
    "date": "2025-06-04",
    "method": "Cash",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay043",
    "invoiceId": "inv059",
    "studentName": "Rida Al-Nouri",
    "amount": 1500,
    "date": "2025-06-04",
    "method": "Online",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay044",
    "invoiceId": "inv061",
    "studentName": "Sawdah Abbasi",
    "amount": 1250,
    "date": "2025-07-11",
    "method": "Online",
    "receivedBy": "Admin",
    "note": "Partial payment, balance due"
  },
  {
    "id": "pay045",
    "invoiceId": "inv063",
    "studentName": "Asiya Iqbal",
    "amount": 4000,
    "date": "2025-07-22",
    "method": "Online",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay046",
    "invoiceId": "inv065",
    "studentName": "Sajid Kazmi",
    "amount": 3500,
    "date": "2025-06-05",
    "method": "Online",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay047",
    "invoiceId": "inv066",
    "studentName": "Qadir Imran",
    "amount": 2625,
    "date": "2025-06-16",
    "method": "Cash",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay048",
    "invoiceId": "inv067",
    "studentName": "Ruqayyah Karimi",
    "amount": 3600,
    "date": "2025-06-09",
    "method": "Online",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay049",
    "invoiceId": "inv068",
    "studentName": "Hussein Ghani",
    "amount": 2625,
    "date": "2025-06-20",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay050",
    "invoiceId": "inv073",
    "studentName": "Rayhana Ghazi",
    "amount": 4000,
    "date": "2025-06-26",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay051",
    "invoiceId": "inv074",
    "studentName": "Sana Al-Farsi",
    "amount": 2500,
    "date": "2025-06-29",
    "method": "Online",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay052",
    "invoiceId": "inv075",
    "studentName": "Zoya Rizvi",
    "amount": 4000,
    "date": "2025-06-09",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay053",
    "invoiceId": "inv076",
    "studentName": "Aisha Rahman",
    "amount": 4000,
    "date": "2025-07-09",
    "method": "Cash",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay054",
    "invoiceId": "inv077",
    "studentName": "Bashir Malik",
    "amount": 3500,
    "date": "2025-07-01",
    "method": "Online",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay055",
    "invoiceId": "inv078",
    "studentName": "Bushra Qadri",
    "amount": 4000,
    "date": "2025-06-12",
    "method": "Bank Transfer",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay056",
    "invoiceId": "inv081",
    "studentName": "Hania Al-Nouri",
    "amount": 1875,
    "date": "2025-07-02",
    "method": "Cash",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay057",
    "invoiceId": "inv084",
    "studentName": "Noura Hussain",
    "amount": 4000,
    "date": "2025-06-28",
    "method": "Bank Transfer",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay058",
    "invoiceId": "inv085",
    "studentName": "Sajid Sajid",
    "amount": 3500,
    "date": "2025-07-06",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay059",
    "invoiceId": "inv086",
    "studentName": "Salman Akhtar",
    "amount": 3500,
    "date": "2025-06-10",
    "method": "Cash",
    "receivedBy": "System",
    "note": "Full payment received"
  },
  {
    "id": "pay060",
    "invoiceId": "inv087",
    "studentName": "Salma Ghani",
    "amount": 4000,
    "date": "2025-06-20",
    "method": "Bank Transfer",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay061",
    "invoiceId": "inv088",
    "studentName": "Fatima Al-Nouri",
    "amount": 4000,
    "date": "2025-06-28",
    "method": "Online",
    "receivedBy": "Accountant",
    "note": "Full payment received"
  },
  {
    "id": "pay062",
    "invoiceId": "inv089",
    "studentName": "Sawdah Latif",
    "amount": 3000,
    "date": "2025-06-01",
    "method": "Online",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay063",
    "invoiceId": "inv090",
    "studentName": "Bushra Yousaf",
    "amount": 4000,
    "date": "2025-06-27",
    "method": "Online",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay064",
    "invoiceId": "inv091",
    "studentName": "Ali Rahman",
    "amount": 3500,
    "date": "2025-07-17",
    "method": "Cash",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay065",
    "invoiceId": "inv092",
    "studentName": "Uzma Al-Farsi",
    "amount": 3600,
    "date": "2025-06-19",
    "method": "Bank Transfer",
    "receivedBy": "Admin",
    "note": "Full payment received"
  },
  {
    "id": "pay066",
    "invoiceId": "inv501",
    "studentName": "Luqman Rehman",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay067",
    "invoiceId": "inv502",
    "studentName": "Ali Nawaz",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay068",
    "invoiceId": "inv503",
    "studentName": "Sufyan Imran",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay069",
    "invoiceId": "inv504",
    "studentName": "Bushra Yousaf",
    "amount": 4000,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay070",
    "invoiceId": "inv505",
    "studentName": "Bushra Yousaf",
    "amount": 4000,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay071",
    "invoiceId": "inv506",
    "studentName": "Hassan Khalid",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay072",
    "invoiceId": "inv507",
    "studentName": "Noman Tariq",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay073",
    "invoiceId": "inv508",
    "studentName": "Sajid Sajid",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay074",
    "invoiceId": "inv509",
    "studentName": "Aaliyah Ghani",
    "amount": 2500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay075",
    "invoiceId": "inv510",
    "studentName": "Ruqayyah Lodhi",
    "amount": 2000,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay076",
    "invoiceId": "inv511",
    "studentName": "Sawdah Latif",
    "amount": 4000,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay077",
    "invoiceId": "inv512",
    "studentName": "Noman Tariq",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay078",
    "invoiceId": "inv513",
    "studentName": "Lubna Karimi",
    "amount": 4000,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay079",
    "invoiceId": "inv514",
    "studentName": "Ruqayyah Karimi",
    "amount": 4000,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay080",
    "invoiceId": "inv515",
    "studentName": "Noman Aslam",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay081",
    "invoiceId": "inv516",
    "studentName": "Habib Ghani",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay082",
    "invoiceId": "inv517",
    "studentName": "Sana Al-Farsi",
    "amount": 2500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay083",
    "invoiceId": "inv518",
    "studentName": "Zakariya Naqvi",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay084",
    "invoiceId": "inv519",
    "studentName": "Sajid Kazmi",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay085",
    "invoiceId": "inv520",
    "studentName": "Sidra Al-Rashid",
    "amount": 2000,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay086",
    "invoiceId": "inv521",
    "studentName": "Kashif Shah",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay087",
    "invoiceId": "inv522",
    "studentName": "Shakir Ghani",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay088",
    "invoiceId": "inv523",
    "studentName": "Hussein Ghani",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay089",
    "invoiceId": "inv524",
    "studentName": "Hamza Akhtar",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay090",
    "invoiceId": "inv525",
    "studentName": "Nadia Bhatti",
    "amount": 4000,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay091",
    "invoiceId": "inv526",
    "studentName": "Uzma Al-Farsi",
    "amount": 4000,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay092",
    "invoiceId": "inv527",
    "studentName": "Ruqayyah Karimi",
    "amount": 4000,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  },
  {
    "id": "pay093",
    "invoiceId": "inv528",
    "studentName": "Luqman Rehman",
    "amount": 3500,
    "date": "2025-09-08",
    "method": "Cash",
    "receivedBy": "Accountant",
    "note": "Extra term invoice payment"
  }
];
export const MONTHLY_REVENUE = [
  { month: "Jan", collected: 18000, outstanding: 5000, expenses: 12000 },
  { month: "Feb", collected: 22000, outstanding: 3500, expenses: 14000 },
  { month: "Mar", collected: 19500, outstanding: 7000, expenses: 13000 },
  { month: "Apr", collected: 25000, outstanding: 2000, expenses: 15500 },
  { month: "May", collected: 28000, outstanding: 4500, expenses: 16000 },
  { month: "Jun", collected: 35000, outstanding: 8750, expenses: 22000 },
  { month: "Jul", collected: 31000, outstanding: 6000, expenses: 19000 },
];
export const HASANAT_PAYOUTS: HasanatPayout[] = [];
export const PAYMENT_METHODS = ["Cash", "Bank Transfer", "Online", "Cheque", "Other"] as const;
export const INVOICE_STATUSES = ["paid", "pending", "overdue", "partial", "cancelled"] as const;
