export interface Denomination {
  id: string;
  name: string;
  points: number;
  color: string;
  description: string;
  icon: string;
  active: boolean;
}

export interface StockBatch {
  id: string;
  denominationId: string;
  denominationName: string;
  quantity: number;
  remaining: number;
  addedDate: string;
  addedBy: string;
  note: string;
}

export interface Distribution {
  id: string;
  batchId: string;
  denominationId: string;
  denominationName: string;
  recipientType: "student" | "faculty";
  recipientName: string;
  recipientClass: string;
  quantity: number;
  reason: string;
  issuedDate: string;
  issuedBy: string;
  status: "active" | "redeemed" | "returned";
}

export interface Redemption {
  id: string;
  distributionId: string;
  studentName: string;
  reward: string;
  pointsUsed: number;
  date: string;
  approvedBy: string;
}

export const DENOMINATIONS: Denomination[] = [
  { id: "den1", name: "Bronze Card", points: 50, color: "#cd7f32", description: "Awarded for daily attendance", icon: "⭐", active: true },
  { id: "den2", name: "Silver Card", points: 150, color: "#9ca3af", description: "Awarded for Juz completion", icon: "🌟", active: true },
  { id: "den3", name: "Gold Card", points: 500, color: "#d97706", description: "Awarded for Hifz milestone", icon: "✨", active: true },
  { id: "den4", name: "Platinum Card", points: 1000, color: "#7c3aed", description: "Awarded for full Hifz completion", icon: "💎", active: true },
  { id: "den5", name: "Diamond Card", points: 2500, color: "#2563eb", description: "Highest honour – Khatam Al-Quran", icon: "👑", active: false },
];

export const STOCK_BATCHES: StockBatch[] = [
  { id: "bat1", denominationId: "den1", denominationName: "Bronze Card", quantity: 200, remaining: 120, addedDate: "2025-01-10", addedBy: "Admin", note: "January batch" },
  { id: "bat2", denominationId: "den2", denominationName: "Silver Card", quantity: 100, remaining: 65, addedDate: "2025-01-10", addedBy: "Admin", note: "January batch" },
  { id: "bat3", denominationId: "den3", denominationName: "Gold Card", quantity: 50, remaining: 28, addedDate: "2025-01-10", addedBy: "Admin", note: "January batch" },
  { id: "bat4", denominationId: "den4", denominationName: "Platinum Card", quantity: 20, remaining: 12, addedDate: "2025-01-10", addedBy: "Admin", note: "January batch" }
];

export const DISTRIBUTIONS: Distribution[] = [
  {
    "id": "dist1",
    "batchId": "bat4",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Noura Nasir",
    "recipientClass": "Hifz A",
    "quantity": 2,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-07-10",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist2",
    "batchId": "bat1",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Sajid Ghani",
    "recipientClass": "Hifz A",
    "quantity": 1,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-08-30",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist3",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Zoya Rizvi",
    "recipientClass": "Tajweed Adv",
    "quantity": 2,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-06-10",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist4",
    "batchId": "bat4",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Samia Karimi",
    "recipientClass": "Tajweed Adv",
    "quantity": 4,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-06-22",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist5",
    "batchId": "bat2",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Safiyyah Nawaz",
    "recipientClass": "Qaidah Girls A",
    "quantity": 2,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-05-31",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist6",
    "batchId": "bat4",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Shakir Ghani",
    "recipientClass": "Hifz B",
    "quantity": 2,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-08-06",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist7",
    "batchId": "bat4",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Farida Qazi",
    "recipientClass": "Qaidah Girls A",
    "quantity": 2,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-07-31",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist8",
    "batchId": "bat2",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Zainab Siddiqui",
    "recipientClass": "Tajweed Adv",
    "quantity": 4,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-10-16",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist9",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Mariam Akhtar",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-07-05",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist10",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Sumayya Iqbal",
    "recipientClass": "Tajweed Adv",
    "quantity": 4,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-07-24",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist11",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Ali Farooq",
    "recipientClass": "Hifz A",
    "quantity": 1,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-09-30",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist12",
    "batchId": "bat1",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Ahmed Qazi",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-08-05",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist13",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Fatima Zaidi",
    "recipientClass": "Qaidah Girls A",
    "quantity": 2,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-10-02",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist14",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Hina Anwar",
    "recipientClass": "Qaidah Girls A",
    "quantity": 5,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-07-01",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist15",
    "batchId": "bat3",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Rayhana Ghazi",
    "recipientClass": "Tajweed Adv",
    "quantity": 1,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-09-24",
    "issuedBy": "Ustadha Fatima",
    "status": "redeemed"
  },
  {
    "id": "dist16",
    "batchId": "bat2",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Safiyyah Nawaz",
    "recipientClass": "Qaidah Girls A",
    "quantity": 5,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-02",
    "issuedBy": "Ustadha Fatima",
    "status": "redeemed"
  },
  {
    "id": "dist17",
    "batchId": "bat4",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Zain Zaidi",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-08-31",
    "issuedBy": "Ustadha Fatima",
    "status": "redeemed"
  },
  {
    "id": "dist18",
    "batchId": "bat3",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Jamil Kazmi",
    "recipientClass": "Hifz A",
    "quantity": 1,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-08-13",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist19",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Nadia Bhatti",
    "recipientClass": "Tajweed Adv",
    "quantity": 3,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-08-07",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist20",
    "batchId": "bat3",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Shakir Bukhari",
    "recipientClass": "Hifz A",
    "quantity": 2,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-06-27",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist21",
    "batchId": "bat2",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Uzma Al-Farsi",
    "recipientClass": "Tajweed Adv",
    "quantity": 4,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-08-09",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist22",
    "batchId": "bat1",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Bashir Malik",
    "recipientClass": "Hifz B",
    "quantity": 5,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-06-19",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist23",
    "batchId": "bat1",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Sajid Ghani",
    "recipientClass": "Hifz A",
    "quantity": 1,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-06-12",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist24",
    "batchId": "bat1",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Sara Hussain",
    "recipientClass": "Hifz A",
    "quantity": 5,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-17",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist25",
    "batchId": "bat1",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Sidra Al-Rashid",
    "recipientClass": "Islamic Studies Yr 1",
    "quantity": 4,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-10-08",
    "issuedBy": "Ustadha Fatima",
    "status": "returned"
  },
  {
    "id": "dist26",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Abdullah Rizvi",
    "recipientClass": "Hifz A",
    "quantity": 1,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-08-07",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist27",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Faisal Al-Farsi",
    "recipientClass": "Hifz B",
    "quantity": 4,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-09-07",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist28",
    "batchId": "bat1",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Harun Khalid",
    "recipientClass": "Hifz A",
    "quantity": 4,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-10-16",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist29",
    "batchId": "bat3",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Qadir Imran",
    "recipientClass": "Hifz A",
    "quantity": 2,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-10-03",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist30",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Maymunah Bhatti",
    "recipientClass": "Hifz A",
    "quantity": 2,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-09-26",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist31",
    "batchId": "bat1",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Qadir Imran",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-07-24",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist32",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Zoya Rizvi",
    "recipientClass": "Tajweed Adv",
    "quantity": 5,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-10",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist33",
    "batchId": "bat2",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Usman Hussain",
    "recipientClass": "Hifz A",
    "quantity": 5,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-08-18",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist34",
    "batchId": "bat4",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Faisal Al-Farsi",
    "recipientClass": "Hifz B",
    "quantity": 5,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-07-21",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist35",
    "batchId": "bat4",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Ruqayyah Karimi",
    "recipientClass": "Tajweed Adv",
    "quantity": 4,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-08-20",
    "issuedBy": "Ustadha Fatima",
    "status": "returned"
  },
  {
    "id": "dist36",
    "batchId": "bat2",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Shakir Ghani",
    "recipientClass": "Hifz B",
    "quantity": 3,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-09-23",
    "issuedBy": "Ustadha Fatima",
    "status": "returned"
  },
  {
    "id": "dist37",
    "batchId": "bat3",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Ali Nawaz",
    "recipientClass": "Hifz B",
    "quantity": 3,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-06-17",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist38",
    "batchId": "bat1",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Harun Khalid",
    "recipientClass": "Hifz A",
    "quantity": 4,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-10-04",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist39",
    "batchId": "bat3",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Ayla Bukhari",
    "recipientClass": "Tajweed Adv",
    "quantity": 5,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-06-23",
    "issuedBy": "Ustadha Fatima",
    "status": "returned"
  },
  {
    "id": "dist40",
    "batchId": "bat4",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Ruqayyah Lodhi",
    "recipientClass": "Islamic Studies Yr 1",
    "quantity": 2,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-07-31",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist41",
    "batchId": "bat1",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Sajid Bukhari",
    "recipientClass": "Hifz A",
    "quantity": 4,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-08",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist42",
    "batchId": "bat2",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Aisha Rahman",
    "recipientClass": "Tajweed Adv",
    "quantity": 5,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-09-25",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist43",
    "batchId": "bat4",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Bushra Qadri",
    "recipientClass": "Tajweed Adv",
    "quantity": 1,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-08-08",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist44",
    "batchId": "bat3",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Sajid Kazmi",
    "recipientClass": "Hifz B",
    "quantity": 3,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-06-23",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist45",
    "batchId": "bat1",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Rida Al-Nouri",
    "recipientClass": "Islamic Studies Yr 1",
    "quantity": 2,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-08-08",
    "issuedBy": "Ustadha Fatima",
    "status": "redeemed"
  },
  {
    "id": "dist46",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Jabir Sheikh",
    "recipientClass": "Hifz B",
    "quantity": 4,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-06-05",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist47",
    "batchId": "bat3",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Sawdah Latif",
    "recipientClass": "Tajweed Adv",
    "quantity": 4,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-06-16",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist48",
    "batchId": "bat4",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Farida Qazi",
    "recipientClass": "Qaidah Girls A",
    "quantity": 3,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-14",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist49",
    "batchId": "bat3",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Shakir Ghani",
    "recipientClass": "Hifz B",
    "quantity": 1,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-07-10",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist50",
    "batchId": "bat1",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Lubna Shafique",
    "recipientClass": "Qaidah Girls A",
    "quantity": 5,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-09-16",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist51",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Habib Ghani",
    "recipientClass": "Hifz B",
    "quantity": 3,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-07-28",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist52",
    "batchId": "bat2",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Lubna Dar",
    "recipientClass": "Tajweed Adv",
    "quantity": 2,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-10-20",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist53",
    "batchId": "bat3",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Hina Rahman",
    "recipientClass": "Hifz A",
    "quantity": 4,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-06-10",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist54",
    "batchId": "bat3",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Usman Hussain",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-10",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist55",
    "batchId": "bat4",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Muhammad Karimi",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-06-30",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist56",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Sajid Sajid",
    "recipientClass": "Hifz B",
    "quantity": 5,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-06-28",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist57",
    "batchId": "bat4",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Uzma Imran",
    "recipientClass": "Qaidah Girls A",
    "quantity": 2,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-06-21",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist58",
    "batchId": "bat3",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Farida Qazi",
    "recipientClass": "Qaidah Girls A",
    "quantity": 2,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-09-23",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist59",
    "batchId": "bat4",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Ahmed Qazi",
    "recipientClass": "Hifz A",
    "quantity": 1,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-08-11",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist60",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Samia Hashmi",
    "recipientClass": "Tajweed Adv",
    "quantity": 4,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-09-13",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist61",
    "batchId": "bat4",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Sumayya Iqbal",
    "recipientClass": "Tajweed Adv",
    "quantity": 5,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-07-15",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist62",
    "batchId": "bat1",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Bashir Al-Nouri",
    "recipientClass": "Hifz A",
    "quantity": 4,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-05",
    "issuedBy": "Ustadha Fatima",
    "status": "redeemed"
  },
  {
    "id": "dist63",
    "batchId": "bat1",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Sufyan Imran",
    "recipientClass": "Hifz B",
    "quantity": 1,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-07-22",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist64",
    "batchId": "bat4",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Yasmin Rehman",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-10-18",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist65",
    "batchId": "bat1",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Hussein Ghani",
    "recipientClass": "Hifz A",
    "quantity": 4,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-07-06",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist66",
    "batchId": "bat4",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Sawdah Al-Nouri",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-06-29",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist67",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Shakir Ghani",
    "recipientClass": "Hifz B",
    "quantity": 4,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-10-14",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist68",
    "batchId": "bat2",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Muhammad Karimi",
    "recipientClass": "Hifz A",
    "quantity": 1,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-07-05",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist69",
    "batchId": "bat2",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Sawdah Al-Nouri",
    "recipientClass": "Hifz A",
    "quantity": 4,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-06-05",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist70",
    "batchId": "bat2",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Majid Khalid",
    "recipientClass": "Hifz A",
    "quantity": 5,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-09-05",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist71",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Ruqayyah Lodhi",
    "recipientClass": "Islamic Studies Yr 1",
    "quantity": 4,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-10-01",
    "issuedBy": "Ustadha Fatima",
    "status": "redeemed"
  },
  {
    "id": "dist72",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Aaliyah Ghani",
    "recipientClass": "Qaidah Girls A",
    "quantity": 3,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-06-30",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist73",
    "batchId": "bat4",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Aaliyah Ghani",
    "recipientClass": "Qaidah Girls A",
    "quantity": 1,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-10-09",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist74",
    "batchId": "bat2",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Hania Al-Nouri",
    "recipientClass": "Qaidah Girls A",
    "quantity": 5,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-10",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist75",
    "batchId": "bat3",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Lubna Shafique",
    "recipientClass": "Qaidah Girls A",
    "quantity": 1,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-10-27",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist76",
    "batchId": "bat1",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Zoya Pirzada",
    "recipientClass": "Tajweed Adv",
    "quantity": 5,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-06-19",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist77",
    "batchId": "bat3",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Zain Zaidi",
    "recipientClass": "Hifz A",
    "quantity": 5,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-10-18",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist78",
    "batchId": "bat4",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Sidra Al-Rashid",
    "recipientClass": "Islamic Studies Yr 1",
    "quantity": 1,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-08-04",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist79",
    "batchId": "bat2",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Aisha Rahman",
    "recipientClass": "Tajweed Adv",
    "quantity": 3,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-08-08",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist80",
    "batchId": "bat3",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Sara Yousaf",
    "recipientClass": "Tajweed Adv",
    "quantity": 2,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-10-15",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist81",
    "batchId": "bat4",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Sidra Khan",
    "recipientClass": "Tajweed Adv",
    "quantity": 2,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-07-05",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist82",
    "batchId": "bat4",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Ayla Bukhari",
    "recipientClass": "Tajweed Adv",
    "quantity": 2,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-12",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist83",
    "batchId": "bat1",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Noura Hussain",
    "recipientClass": "Tajweed Adv",
    "quantity": 1,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-07-20",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist84",
    "batchId": "bat1",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Imran Qadri",
    "recipientClass": "Hifz B",
    "quantity": 5,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-10-27",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist85",
    "batchId": "bat1",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Yahya Farooq",
    "recipientClass": "Hifz A",
    "quantity": 2,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-10-05",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist86",
    "batchId": "bat2",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Rida Al-Nouri",
    "recipientClass": "Islamic Studies Yr 1",
    "quantity": 1,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-09-05",
    "issuedBy": "Ustadha Fatima",
    "status": "returned"
  },
  {
    "id": "dist87",
    "batchId": "bat3",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Salman Akhtar",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-17",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist88",
    "batchId": "bat2",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Jabir Raza",
    "recipientClass": "Hifz B",
    "quantity": 4,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-07-10",
    "issuedBy": "Ustadha Fatima",
    "status": "returned"
  },
  {
    "id": "dist89",
    "batchId": "bat3",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Noura Hussain",
    "recipientClass": "Tajweed Adv",
    "quantity": 2,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-10-01",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist90",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Salma Ghani",
    "recipientClass": "Tajweed Adv",
    "quantity": 2,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-08-29",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist91",
    "batchId": "bat4",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Jabir Raza",
    "recipientClass": "Hifz B",
    "quantity": 4,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-09-04",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist92",
    "batchId": "bat2",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Mustafa Pirzada",
    "recipientClass": "Hifz A",
    "quantity": 2,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-10-23",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist93",
    "batchId": "bat4",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Ibrahim Imran",
    "recipientClass": "Hifz B",
    "quantity": 1,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-06-05",
    "issuedBy": "Ustadha Fatima",
    "status": "redeemed"
  },
  {
    "id": "dist94",
    "batchId": "bat1",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Ruqayyah Lodhi",
    "recipientClass": "Islamic Studies Yr 1",
    "quantity": 1,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-07-01",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist95",
    "batchId": "bat4",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Uzma Imran",
    "recipientClass": "Qaidah Girls A",
    "quantity": 5,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-07-01",
    "issuedBy": "Sheikh Ibrahim",
    "status": "redeemed"
  },
  {
    "id": "dist96",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Noman Tariq",
    "recipientClass": "Hifz B",
    "quantity": 4,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-07-10",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist97",
    "batchId": "bat1",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Yahya Farooq",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-06-11",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist98",
    "batchId": "bat4",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Sidra Al-Rashid",
    "recipientClass": "Islamic Studies Yr 1",
    "quantity": 3,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-08-21",
    "issuedBy": "Ustadha Fatima",
    "status": "active"
  },
  {
    "id": "dist99",
    "batchId": "bat3",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Fariha Qureshi",
    "recipientClass": "Qaidah Girls A",
    "quantity": 5,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-06-17",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist100",
    "batchId": "bat2",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Noman Kazmi",
    "recipientClass": "Hifz A",
    "quantity": 3,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-09-22",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist101",
    "batchId": "bat3",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Bushra Yousaf",
    "recipientClass": "Tajweed Adv",
    "quantity": 5,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-06-30",
    "issuedBy": "Qari Yusuf",
    "status": "redeemed"
  },
  {
    "id": "dist102",
    "batchId": "bat3",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Ruqayyah Shah",
    "recipientClass": "Qaidah Girls A",
    "quantity": 4,
    "reason": "Memorised 2 new Surahs",
    "issuedDate": "2025-09-12",
    "issuedBy": "Ustadha Fatima",
    "status": "redeemed"
  },
  {
    "id": "dist103",
    "batchId": "bat4",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Salma Ghani",
    "recipientClass": "Tajweed Adv",
    "quantity": 1,
    "reason": "Completed Juz milestone",
    "issuedDate": "2025-09-10",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  },
  {
    "id": "dist104",
    "batchId": "bat3",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Zakariya Naqvi",
    "recipientClass": "Hifz B",
    "quantity": 2,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-10-17",
    "issuedBy": "Ustadha Fatima",
    "status": "returned"
  },
  {
    "id": "dist105",
    "batchId": "bat1",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Maryam Hashmi",
    "recipientClass": "Islamic Studies Yr 1",
    "quantity": 1,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-07-27",
    "issuedBy": "Qari Yusuf",
    "status": "active"
  },
  {
    "id": "dist106",
    "batchId": "bat3",
    "denominationId": "den4",
    "denominationName": "Platinum Card",
    "recipientType": "student",
    "recipientName": "Sajid Kazmi",
    "recipientClass": "Hifz B",
    "quantity": 1,
    "reason": "Excellent Tajweed exam performance",
    "issuedDate": "2025-07-04",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist107",
    "batchId": "bat1",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Ruqayyah Karimi",
    "recipientClass": "Tajweed Adv",
    "quantity": 3,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-08-05",
    "issuedBy": "Ustadha Fatima",
    "status": "returned"
  },
  {
    "id": "dist108",
    "batchId": "bat3",
    "denominationId": "den1",
    "denominationName": "Bronze Card",
    "recipientType": "student",
    "recipientName": "Hassan Al-Nouri",
    "recipientClass": "Hifz B",
    "quantity": 1,
    "reason": "Perfect weekly attendance",
    "issuedDate": "2025-07-11",
    "issuedBy": "Qari Yusuf",
    "status": "returned"
  },
  {
    "id": "dist109",
    "batchId": "bat2",
    "denominationId": "den2",
    "denominationName": "Silver Card",
    "recipientType": "student",
    "recipientName": "Uzma Al-Farsi",
    "recipientClass": "Tajweed Adv",
    "quantity": 5,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-09-08",
    "issuedBy": "Sheikh Ibrahim",
    "status": "returned"
  },
  {
    "id": "dist110",
    "batchId": "bat2",
    "denominationId": "den3",
    "denominationName": "Gold Card",
    "recipientType": "student",
    "recipientName": "Sumayya Iqbal",
    "recipientClass": "Tajweed Adv",
    "quantity": 3,
    "reason": "Helping classmates in class activity",
    "issuedDate": "2025-09-25",
    "issuedBy": "Sheikh Ibrahim",
    "status": "active"
  }
];
export const REDEMPTIONS: Redemption[] = [];
