/** @deprecated Import from `@mms/shared` — shim for legacy imports. */
export {
  type PermissionAction as Action,
  ACTIVITY_ACTION_REGISTRY,
  ACTIVITY_ACTION_VALUES as ACTION_TYPES,
  type ActivityAction,
  type ActivityLog,
  ACTIONS,
  DEFAULT_ROLES,
  DEFAULT_USER_ACTIVITY_LOGS,
  DEFAULT_WORKSPACE_ROLES,
  DEFAULT_WORKSPACE_USERS,
  cloneDefaultWorkspaceRoles,
  filterRbacModulesForSettings,
  groupRbacModulesForPermissionsNav,
  RBAC_PERMISSION_NAV,
  findWorkspaceRole,
  isRbacModuleEnabled,
  resolveWorkspaceRole,
  MODULES,
  rbacModuleSystemId,
  RBAC_SYSTEM_MODULE_ID,
  type PermissionMap,
  PERMISSION_ACTIONS,
  RBAC_MODULE_REGISTRY,
  type RbacModuleDef,
  SAMPLE_ACTIVITY_LOGS,
  SAMPLE_USERS,
  type SystemUser,
  type UserStatus,
  USER_STATUS_REGISTRY,
  USER_STATUS_VALUES as STATUS_OPTIONS,
  type WorkspaceRole as Role,
  type WorkspaceUser,
  normalizeSystemUser,
  normalizeWorkspaceUser,
  userStatusMeta,
  activityActionMeta,
} from '@mms/shared';
